/* DROP TABLES SCRIPT */

SET ECHO ON;
SET foreign_key_checks = 0;

DROP TABLE CARSALEMANIFEST;

DROP TABLE CARSALE;
DROP TABLE CARSALESPERSON;

DROP TABLE CARCUSTOMER;
DROP TABLE CARNEWCAR;
DROP TABLE CARREGISTRATION;
DROP TABLE CARSALESURVEY;
DROP TABLE CARWARRANTY;

