/*WARRANTY*/

INSERT INTO CARWARRANTY VALUES ('None', 0.00, 0);
INSERT INTO CARWARRANTY VALUES ('Manufacturer', 0.00, 36);
INSERT INTO CARWARRANTY VALUES ('Super', 0.00, 60);
INSERT INTO CARWARRANTY VALUES ('Ultra', 0.00, 74);

